print("Please enter the following information:")

first_name = input("First name: ")
last_name = input("Last name: ")
email = input("Email address: ")
phone_number = input("Phone number: ")
job_title = input("Job title: ")
id_number = input("ID Number: ")

print("\nThe ID Card is:")
print("----------------------------------------")
print(f"{last_name.upper()}, {first_name}")
print(f"{job_title.title()}")
print(f"ID: {id_number}\n")
print(f"{email.lower()}")
print(f"{phone_number}")
print("----------------------------------------")

hair_color = input("Hair color: ")
eye_color = input("Eye color: ")

month_started = input("Month started: ")
advanced_training = input("Completed advanced training (Yes/No): ")

print("\nThe updated ID Card is:")
print("----------------------------------------")
print(f"{last_name.upper()}, {first_name}")
print(f"{job_title.title()}")
print(f"ID: {id_number}\n")
print(f"{email.lower()}")
print(f"{phone_number}\n")
print(f"Hair: {hair_color:<15} Eyes: {eye_color}")
print(f"Month: {month_started:<15} Training: {advanced_training}")
print("----------------------------------------")
