print("Please enter the following:")

adjective1 = input("adjective: ")
animal = input("animal: ")
verb1 = input("verb: ")
exclamation = input("exclamation: ").capitalize()
verb2 = input("verb: ")
verb3 = input("verb: ")

noun1 = input("noun: ")
place = input("place: ")
adjective2 = input("adjective: ")
plural_noun = input("plural noun: ")

print("\nYour story is:\n")
print(f"The other day, I was really in trouble. It all started when I saw a very")
print(f"{adjective1} {animal} {verb1} down the hallway. \"{exclamation}!\" I yelled. But all")
print(f"I could think to do was to {verb2} over and over. Miraculously,")
print(f"that caused it to stop, but not before it tried to {verb3}")
print(f"right in front of my family. Just then, a {noun1} appeared out of nowhere,")
print(f"and we all had to run to {place} to escape the {adjective2} {plural_noun}.")
print(f"It was a day to remember!")